# Generated by Django 3.0.6 on 2022-04-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0002_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='icon',
            field=models.ImageField(default='loc.png', upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='iconname',
            field=models.CharField(default='iconname', max_length=200),
        ),
    ]
