# Generated by Django 3.0.6 on 2022-05-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0003_auto_20220428_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.CharField(max_length=200),
        ),
    ]
